name: tnef

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                work_dir:
                    - ./
        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                  go-version: '1.24.4'

            - name: Lint
              uses: golangci/golangci-lint-action@v8
              with:
                  version: v2
                  working-directory: ${{ matrix.work_dir }}
                  config: .golangci.yaml

            - name: Test
              working-directory: ${{ matrix.work_dir }}
              run: |
                  go mod tidy
                  go test -v ./...
